spring.application.name=beanbank-app
spring.security.user.name=${SECURITY_USERNAME:root}
spring.security.user.password=${SECURITY_PASSWORD:root}

logging.pattern.console=${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}
